### ISSUE TITLE
node_modules folder exluded in .gitignore file

### ISSUE THREAD

**Issue by aronmal** [migueldamota/custom-deployer#2]
Why is the `node_modules` folder excluded in the `.gitignore` file and versioned?

**Comment by migueldamota** [comment]
> Why is the `node_modules` folder excluded in the `.gitignore` file and versioned?

I got an error that modules weren't found because GitHub Actions didn't install any modules after initializing the deployer action. The action doesn't exist anymore, so I can't show you the error right now.
